
title: My Resume
url: 'http://akinladiko.github.io'
baseurl: '/CV' #change it according to your repository name



# Profile information
yourname: Akinla Diko Omari  ## put your name
title: 'Student at Padjadjaran University'  ## your title
location: Jakarta, Indonesia


## Social Profiles
facebook: http://www.instagram.com/akinladiko  ## your facebook account url
twitter: http://www.twitter.com/dikooomar  ## your twitter account url
linkedin: http://www.linkedin.com/in/akinla-diko-25baa3220/  ## your linkedin account url
dribbble: http://www.github.com/akinladiko  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
